export enum CROP_STATUS {
  PLANNED = 'PLANNED',
  PLANTED = 'PLANTED',
  GROWING = 'GROWING',
  FLOWERING = 'FLOWERING',
  FRUITING = 'FRUITING',
  HARVESTING = 'HARVESTING',
  FINISHED = 'FINISHED',
}
